---
title: "Data_Processing_ DL_Papers_C"
output: html_document
date: "2024-09-29"
---

```{r,warning=FALSE,message=FALSE}
library(dplyr)
library(tidyr)
library(readr)
continuous_dataset <- read_csv("continuous dataset.csv")
View(continuous_dataset)
```


```{r}
glimpse(continuous_dataset)

```

```{r}
library(ggplot2)

ggplot(continuous_dataset, aes(x = datetime, y = nat_demand)) +
  geom_line(color = "blue") +
  labs(title = "National Demand Over Time", 
       x = "Time", 
       y = "National Demand") +
  theme_bw()

```
```{r}
library(tidyr)

# Gather temperature data for faceting
temp_long <- continuous_dataset %>%
  select(datetime, T2M_toc, T2M_san, T2M_dav) %>%
  pivot_longer(cols = starts_with("T2M"), names_to = "Location", values_to = "Temperature")

ggplot(temp_long, aes(x = datetime, y = Temperature, color = Location)) +
  geom_line() +
  facet_wrap(~ Location, scales = "free_y") +
  labs(title = "Temperature Trends Over Time by Location",
       x = "Time", 
       y = "Temperature (°C)") +
  theme_bw()

```

```{r}

ggplot(continuous_dataset, aes(x = factor(holiday), y = nat_demand, fill = factor(holiday))) +
  geom_boxplot() +
  labs(title = "National Demand on Holidays vs Non-Holidays",
       x = "Holiday (0 = No, 1 = Yes)",
       y = "National Demand",
       fill = "Holiday") +
  theme_bw()
```
```{r}
ggplot(continuous_dataset, aes(x = factor(school), y = nat_demand, fill = factor(school))) +
  geom_boxplot() +
  labs(title = "National Demand on Schools vs Non-Schools",
       x = "School (0 = No, 1 = Yes)",
       y = "National Demand",
       fill = "School") +
  theme_bw()
```

```{r}

reduced_dataset <- continuous_dataset %>%
  select(datetime, nat_demand, T2M_toc, T2M_san, T2M_dav, QV2M_toc, QV2M_san, QV2M_dav, 
         TQL_toc, TQL_san, TQL_dav, W2M_toc, W2M_san, W2M_dav) %>%
  mutate(
    T2M = rowMeans(select(., T2M_toc, T2M_san, T2M_dav), na.rm = TRUE),
    QV2M = rowMeans(select(., QV2M_toc, QV2M_san, QV2M_dav), na.rm = TRUE),
    TQL = rowMeans(select(., TQL_toc, TQL_san, TQL_dav), na.rm = TRUE),
    W2M = rowMeans(select(., W2M_toc, W2M_san, W2M_dav), na.rm = TRUE)
  ) %>%
 
  select(datetime, nat_demand, T2M, QV2M, TQL, W2M)


head(reduced_dataset)

```

